#!/usr/bin/env bash
# Local prod-mirror — full distributed stack (Postgres + Redis + Celery + MinIO)
# so you can reproduce architecture-v2 bugs that inline-mode hides.
#
# Usage:
#   ./scripts/setup-local-prod.sh           # idempotent — safe to re-run
#   ./scripts/setup-local-prod.sh teardown  # stop everything cleanly
#
# What it does:
#   1. Brings up docker-compose services (Postgres / Redis / MinIO).
#   2. Runs alembic upgrade head against the local Postgres.
#   3. Generates backend/.env.local-prod (env vars for the prod-mirror).
#   4. Prints the two commands you need in separate terminals:
#        Terminal A: backend (uvicorn) on port 8002 (8001 is launchd-managed)
#        Terminal B: Celery worker
#
# Critically: this DOES NOT touch your existing launchd backend on :8001 or
# your SQLite cmds.db. Different port, different DB, different process. The
# old inline setup keeps working alongside.

set -e

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BACKEND="$ROOT/backend"
ENV_FILE="$BACKEND/.env.local-prod"
COMPOSE_PROJECT="cmds-local-prod"

# Color helpers
say()   { printf "\033[1;36m▸ %s\033[0m\n" "$*"; }
ok()    { printf "\033[1;32m✓ %s\033[0m\n" "$*"; }
warn()  { printf "\033[1;33m⚠ %s\033[0m\n" "$*"; }
die()   { printf "\033[1;31m✗ %s\033[0m\n" "$*" >&2; exit 1; }

# ─────────────────────────────────────────────────────────────────────────
# Teardown
# ─────────────────────────────────────────────────────────────────────────
if [[ "${1:-}" == "teardown" ]]; then
    say "Stopping docker-compose services"
    cd "$ROOT"
    docker compose -p "$COMPOSE_PROJECT" -f docker-compose.yml -f docker-compose.local-prod.yml down
    ok "Done. Volumes preserved (data survives). Use 'docker compose -p $COMPOSE_PROJECT down -v' to wipe."
    exit 0
fi

# ─────────────────────────────────────────────────────────────────────────
# Preflight
# ─────────────────────────────────────────────────────────────────────────
say "Preflight checks"

docker info >/dev/null 2>&1 || die "Docker daemon not running. Start Docker Desktop first."
ok "Docker daemon up"

command -v uv >/dev/null 2>&1 || die "uv not found. Install: https://docs.astral.sh/uv/"
ok "uv installed"

cd "$ROOT"
[[ -f docker-compose.yml ]] || die "docker-compose.yml not found in repo root"
[[ -d backend/alembic ]]    || die "backend/alembic not found"
ok "Repo structure looks right"

# ─────────────────────────────────────────────────────────────────────────
# 1. Bring up infra
# ─────────────────────────────────────────────────────────────────────────
say "Starting Postgres + Redis + MinIO (docker compose)"
docker compose -p "$COMPOSE_PROJECT" -f docker-compose.yml -f docker-compose.local-prod.yml up -d postgres redis minio minio-init

# Wait for Postgres + Redis to be healthy
for svc in postgres redis; do
    say "Waiting for $svc to be healthy"
    for i in {1..30}; do
        state=$(docker inspect -f '{{.State.Health.Status}}' "${COMPOSE_PROJECT}-${svc}-1" 2>/dev/null || echo "starting")
        [[ "$state" == "healthy" ]] && { ok "$svc healthy"; break; }
        sleep 1
    done
done

# ─────────────────────────────────────────────────────────────────────────
# 2. Env file for the prod-mirror backend
# ─────────────────────────────────────────────────────────────────────────
if [[ -f "$ENV_FILE" ]]; then
    ok "$ENV_FILE already exists — skipping (delete it if you want to regenerate)"
else
    say "Writing $ENV_FILE"
cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/setup-local-prod.sh — local prod-mirror env.
# This is the CRITICAL flag — switches dispatch from threading.Timer to Celery.
TASK_EXECUTOR=celery

# Local Postgres in docker-compose
DATABASE_URL=postgresql+asyncpg://cmds:cmds@localhost:5433/cmds
SYNC_DATABASE_URL=postgresql+psycopg2://cmds:cmds@localhost:5433/cmds

# Local Redis broker (same image as prod)
REDIS_URL=redis://localhost:6379/0
CELERY_BROKER_URL=redis://localhost:6379/1

# Storage — local filesystem
STORAGE_BACKEND=local
STORAGE_LOCAL_ROOT=./storage

# Diagram raster fallback (resvg binary lives at backend/tools/resvg/)
EMBED_REGEN_DIAGRAM_IN_DOCX=true

# Required secrets — COPY VALUES FROM YOUR RAILWAY BACKEND VARIABLES TAB.
# Without these, Gemini/Claude/etc calls fail.
GEMINI_API_KEY=__paste_from_railway__
ANTHROPIC_API_KEY=__paste_from_railway__
ENCRYPTION_KEY=__paste_from_railway__

# (Optional) Multi-OCR providers — copy from Railway if you use them.
MATHPIX_APP_ID=
MATHPIX_APP_KEY=
SARVAM_API_KEY=

# (Optional) Cap Celery worker concurrency for predictable repro
CELERY_CONCURRENCY=3

# CORS for the local frontend (Vite default + this script's frontend port)
CORS_ORIGINS=http://localhost:5173,http://localhost:5174,http://localhost:5175

# Tighten log level for noisier orchestrator/watchdog tracing
LOG_LEVEL=DEBUG
EOF
    ok "Env file written"
fi

# ─────────────────────────────────────────────────────────────────────────
# 3. Migrations against the prod-mirror Postgres
# ─────────────────────────────────────────────────────────────────────────
say "Running alembic migrations against local Postgres"
cd "$BACKEND"
SYNC_DATABASE_URL=postgresql+psycopg2://cmds:cmds@localhost:5433/cmds \
    DATABASE_URL=postgresql+asyncpg://cmds:cmds@localhost:5433/cmds \
    uv run alembic upgrade head
ok "Schema is at HEAD"

# ─────────────────────────────────────────────────────────────────────────
# 4. Print the two terminal commands
# ─────────────────────────────────────────────────────────────────────────
cat <<EOF

$(printf "\033[1;32m═══════════════════════════════════════════════════════════\033[0m")
$(printf "\033[1;32m  Local prod-mirror is READY.\033[0m")
$(printf "\033[1;32m═══════════════════════════════════════════════════════════\033[0m")

Before starting the servers:
  1. Open $ENV_FILE
  2. Paste GEMINI_API_KEY / ANTHROPIC_API_KEY / ENCRYPTION_KEY
     from Railway → backend service → Variables tab.

Then start in TWO separate terminals:

  Terminal A — backend API (NOTE: port 8002, not 8001):
    cd $BACKEND
    set -a; source .env.local-prod; set +a
    uv run uvicorn app.main:app --reload --reload-dir app --port 8002

  Terminal B — Celery worker (the key difference from inline mode):
    cd $BACKEND
    set -a; source .env.local-prod; set +a
    uv run celery -A app.workers.celery_app worker --loglevel=DEBUG --concurrency=3 \\
        --without-gossip --without-mingle --without-heartbeat

  Optional Terminal C — Flower (Celery monitoring UI on :5555):
    cd $BACKEND
    set -a; source .env.local-prod; set +a
    uv run celery -A app.workers.celery_app flower --port=5555

Frontend (Terminal D, optional):
    cd $ROOT/frontend-v2
    VITE_API_BASE=http://localhost:8002 npm run dev

Your existing setup (launchd on :8001, SQLite cmds.db) is UNAFFECTED.

To stop everything (preserves data):  ./scripts/setup-local-prod.sh teardown
To wipe data too:                     docker compose -p $COMPOSE_PROJECT down -v

EOF
